# Generated by Django 3.2.9 on 2021-11-13 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='users',
            field=models.ManyToManyField(related_name='users', through='InventoryApp.LocationTeam', to=settings.AUTH_USER_MODEL),
        ),
    ]
