# Generated by Django 3.2.9 on 2021-11-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0002_auto_20211111_1636'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locationteam',
            table='location_team',
        ),
    ]
