# Generated by Django 3.2.9 on 2021-11-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0003_alter_locationteam_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
