# Generated by Django 3.2.9 on 2021-11-20 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0004_auto_20211118_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('total', models.FloatField(null=True)),
                ('credits_issued', models.FloatField(null=True)),
                ('paid', models.FloatField(null=True)),
                ('expected_delivery', models.DateTimeField(null=True)),
                ('payment_type', models.CharField(choices=[('COD', 'Cash On Delivery'), ('STRIPE', 'Stripe Credit/Debit'), ('PAYPAL', 'Paypal')], max_length=255, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[(1, 'Process'), (2, 'Completed'), (3, 'Hold')], max_length=2)),
                ('note', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.order')),
            ],
            options={
                'db_table': 'order_item',
                'unique_together': {('order', 'item')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', through='InventoryApp.OrderItem', to='InventoryApp.Item'),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.location'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.vendor'),
        ),
    ]
