# Generated by Django 3.2.9 on 2022-02-04 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0008_receipt_receiptfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.item')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.vendor')),
            ],
            options={
                'db_table': 'vendor_item',
                'unique_together': {('vendor', 'item')},
            },
        ),
    ]
