# Generated by Django 3.2.9 on 2022-02-10 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0009_vendoritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreport',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
